FROM liferay/portal:7.4.3.132-ga132

ENV LIFERAY_WORKSPACE_ENVIRONMENT=test

# Copy JOD integration test runner OSGi bundle (HTTP endpoint for installing test bundles)
COPY --chown=liferay:liferay test/jod-cms-testrunner-osgi/build/libs/jod-cms-testrunner-osgi.jar /opt/liferay/osgi/modules/

# Copy portal.test bundle for LiferayIntegrationTestRule and related test utilities
COPY --chown=liferay:liferay portal-test-libs/com.liferay.portal.test.jar /opt/liferay/osgi/modules/

# Copy all application modules (excluding test modules)
COPY --chown=liferay:liferay deploy/*.jar /opt/liferay/osgi/modules/

# 8080 - Liferay HTTP (also serves the /o/jod-testrunner test runner endpoint)
EXPOSE 8080

USER liferay:liferay
WORKDIR /opt/liferay
ENTRYPOINT ["/usr/local/bin/liferay_entrypoint.sh"]
