plugins {
  id 'java-library'
  id 'jacoco'
}

repositories {
  mavenCentral()
  maven {
    url "https://repository.liferay.com/nexus/content/groups/public"
  }
}

dependencies {
  api libs.bnd
  api libs.junit
  api libs.hamcrest.core
  api libs.osgi.core
}

jar {
  manifest {
    attributes(
      'Bundle-Name': 'JOD CMS Integration Test Runner (client + runtime)',
      'Bundle-SymbolicName': 'oph.jod.cms.testrunner.client',
      'Bundle-Version': '1.0.0'
    )
  }
}

jacoco {
  toolVersion = libs.versions.jacoco.get()
}

tasks.named('test') {
  finalizedBy tasks.named('jacocoTestReport')
}

tasks.named('jacocoTestReport') {
  dependsOn tasks.named('test')
  reports {
    xml.required = true
    html.required = true
  }
}
